export const CHANGE_COLLAPSED = "CHANGE_COLLAPSED";
export const GET_BOOKS = "GET_BOOKS";
export const GET_ARTICLES="GET_ARTICLES";
export const DELETE_ARTICLE="DELETE_ARTICLE";
export const GET_CLASSIFY="GET_CLASSIFY";
export const DELETE_CLASSIFY="DELETE_CLASSIFY";